FROM debian:bullseye-slim

ARG UID
ARG GID

RUN usermod --non-unique --uid ${UID} www-data
RUN groupmod --non-unique --gid ${GID} www-data

RUN apt-get update

RUN apt-get install -y locales locales-all
ENV LANG de_DE.UTF-8
ENV LANGUAGE de_DE:en
ENV LC_ALL de_DE.UTF-8
ENV TZ "Europe/Berlin"

RUN apt-get install -y curl gnupg2 htop nano wget zip ssh nginx supervisor
RUN apt-get install -y libzip-dev libxml2-dev libgearman8 libgearman-dev lsb-release apt-transport-https ca-certificates gnupg

RUN curl -sSLo /usr/share/keyrings/deb.sury.org-php.gpg https://packages.sury.org/php/apt.gpg
RUN sh -c 'echo "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
RUN apt-get update

RUN apt-get install -y php8.1-fpm php8.1-curl php8.1-zip php8.1-dev php8.1-gd php8.1-gearman php8.1-imagick \
    php8.1-mbstring php8.1-memcached php8.1-intl php8.1-cli php8.1-soap php8.1-calendar \
    php8.1-mysql php8.1-mysqli php8.1-pdo php8.1-xdebug php8.1-xml php8.1-redis \
    php8.1-grpc php8.1-bcmath php8.1-opcache php8.1-sqlite3

COPY ./config/conf.d/20-xdebug.ini /etc/php/8.1/fpm/conf.d/20-xdebug.ini
COPY ./config/conf.d/20-timezone.ini /etc/php/8.1/fpm/conf.d/20-timezone.ini
COPY ./config/conf.d/20-memorylimit.ini /etc/php/8.1/fpm/conf.d/20-memorylimit.ini
COPY ./config/conf.d/20-xdebug-cli.ini /etc/php/8.1/cli/conf.d/20-xdebug-cli.ini
COPY ./config/conf.d/20-memorylimit.ini /etc/php/8.1/cli/conf.d/20-memorylimit.ini
COPY ./config/conf.d/20-timezone.ini /etc/php/8.1/cli/conf.d/20-timezone.ini
RUN unlink /etc/php/8.1/cli/conf.d/20-xdebug.ini

COPY ./config/pool.d/php81.conf /etc/php/8.1/fpm/php-fpm.conf
RUN update-alternatives --install /usr/bin/php-fpm php-fpm /usr/sbin/php-fpm8.1 20

RUN apt-get clean

RUN mkdir -p /var/lib/php/session
RUN chmod 777 -R /var/lib/php/session

COPY ./config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./config/site.conf /etc/nginx/sites-available/default
COPY ./index.php /www/index.php

WORKDIR /var/www

CMD ["/usr/bin/supervisord"]