FROM debian:bullseye-slim

ARG UID
ARG GID

RUN usermod --non-unique --uid ${UID} www-data
RUN groupmod --non-unique --gid ${GID} www-data

RUN apt-get update

RUN apt-get install -y locales locales-all
ENV LANG de_DE.UTF-8
ENV LANGUAGE de_DE:en
ENV LC_ALL de_DE.UTF-8
ENV TZ "Europe/Berlin"

RUN apt-get install -y curl gnupg2 htop nano wget zip ssh nginx supervisor memcached redis gearman
RUN echo "daemonize no" >> /etc/redis/redis.conf
RUN apt-get install -y libzip-dev libxml2-dev libgearman8 libgearman-dev lsb-release apt-transport-https ca-certificates gnupg

RUN curl -sSLo /usr/share/keyrings/deb.sury.org-php.gpg https://packages.sury.org/php/apt.gpg
RUN sh -c 'echo "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
RUN apt-get update

RUN apt-get install -y php7.4-fpm php7.4-curl php7.4-zip php7.4-dev php7.4-gd php7.4-gearman php7.4-imagick \
    php7.4-mbstring php7.4-memcached php7.4-intl php7.4-cli php7.4-soap php7.4-calendar \
    php7.4-mysqli php7.4-pdo php7.4-mysql php7.4-xdebug php7.4-redis \
    php7.4-json php7.4-xml php7.4-grpc php7.4-bcmath php7.4-opcache

COPY ./config/conf.d/20-xdebug.ini /etc/php/7.4/fpm/conf.d/20-xdebug.ini
COPY ./config/conf.d/20-timezone.ini /etc/php/7.4/fpm/conf.d/20-timezone.ini
COPY ./config/conf.d/20-memorylimit.ini /etc/php/7.4/fpm/conf.d/20-memorylimit.ini
COPY ./config/conf.d/20-xdebug-cli.ini /etc/php/7.4/cli/conf.d/20-xdebug-cli.ini
COPY ./config/conf.d/20-memorylimit.ini /etc/php/7.4/cli/conf.d/20-memorylimit.ini
COPY ./config/conf.d/20-timezone.ini /etc/php/7.4/cli/conf.d/20-timezone.ini
RUN unlink /etc/php/7.4/cli/conf.d/20-xdebug.ini

COPY ./config/pool.d/php74.conf /etc/php/7.4/fpm/pool.d/www.conf

RUN apt-get clean

COPY ./config/site.conf /etc/nginx/conf.d/default.conf
COPY ./index.php /www/index.php

WORKDIR /